"""align database schema with Eventora architecture

Revision ID: 1ca7934d9c63
Revises: 
Create Date: 2026-08-23 12:26:57.828669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ca7934d9c63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'version', name='uq_event_layout_version')
    )
    op.create_index('ix_layout_event_active', 'venue_layouts', ['event_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_venue_layouts_event_id'), 'venue_layouts', ['event_id'], unique=False)
    op.create_index(op.f('ix_venue_layouts_id'), 'venue_layouts', ['id'], unique=False)
    op.create_index(op.f('ix_venue_layouts_is_active'), 'venue_layouts', ['is_active'], unique=False)
    op.create_table('event_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('zone_type', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('sold_count', sa.Integer(), nullable=False),
    sa.Column('locked_count', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('base_price >= 0', name='ck_base_price_non_negative'),
    sa.CheckConstraint('capacity >= 0', name='ck_zone_capacity_non_negative'),
    sa.CheckConstraint('locked_count >= 0', name='ck_zone_locked_non_negative'),
    sa.CheckConstraint('sold_count >= 0', name='ck_zone_sold_non_negative'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['layout_id'], ['venue_layouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'code', name='uq_event_zone_code')
    )
    op.create_index(op.f('ix_event_zones_event_id'), 'event_zones', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_zones_id'), 'event_zones', ['id'], unique=False)
    op.create_index(op.f('ix_event_zones_is_active'), 'event_zones', ['is_active'], unique=False)
    op.create_index(op.f('ix_event_zones_layout_id'), 'event_zones', ['layout_id'], unique=False)
    op.create_index(op.f('ix_event_zones_zone_type'), 'event_zones', ['zone_type'], unique=False)
    op.create_table('ticket_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('inventory_limit', sa.Integer(), nullable=True),
    sa.Column('sold_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('inventory_limit IS NULL OR inventory_limit >= 0', name='ck_ticket_inventory_non_negative'),
    sa.CheckConstraint('price >= 0', name='ck_ticket_price_non_negative'),
    sa.CheckConstraint('sold_count >= 0', name='ck_ticket_sold_non_negative'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['event_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'name', name='uq_event_ticket_type')
    )
    op.create_index(op.f('ix_ticket_types_event_id'), 'ticket_types', ['event_id'], unique=False)
    op.create_index(op.f('ix_ticket_types_id'), 'ticket_types', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_types_is_active'), 'ticket_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_ticket_types_zone_id'), 'ticket_types', ['zone_id'], unique=False)
    op.create_table('venue_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('row_label', sa.String(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.CheckConstraint('row_number > 0', name='ck_row_number_positive'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['event_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'row_label', name='uq_zone_row_label'),
    sa.UniqueConstraint('zone_id', 'row_number', name='uq_zone_row_number')
    )
    op.create_index(op.f('ix_venue_rows_event_id'), 'venue_rows', ['event_id'], unique=False)
    op.create_index(op.f('ix_venue_rows_id'), 'venue_rows', ['id'], unique=False)
    op.create_index(op.f('ix_venue_rows_zone_id'), 'venue_rows', ['zone_id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('seat_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_seat_price_non_negative'),
    sa.CheckConstraint('seat_number > 0', name='ck_seat_number_positive'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['venue_rows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['event_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'seat_code', name='uq_event_seat_code'),
    sa.UniqueConstraint('row_id', 'seat_number', name='uq_row_seat_number')
    )
    op.create_index(op.f('ix_seats_event_id'), 'seats', ['event_id'], unique=False)
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.create_index(op.f('ix_seats_is_active'), 'seats', ['is_active'], unique=False)
    op.create_index(op.f('ix_seats_row_id'), 'seats', ['row_id'], unique=False)
    op.create_index(op.f('ix_seats_seat_code'), 'seats', ['seat_code'], unique=False)
    op.create_index(op.f('ix_seats_status'), 'seats', ['status'], unique=False)
    op.create_index(op.f('ix_seats_zone_id'), 'seats', ['zone_id'], unique=False)
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('inventory_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('ticket_type_id', sa.Integer(), nullable=True),
    sa.Column('lock_token', sa.String(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['event_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventories_event_id'), 'inventories', ['event_id'], unique=False)
    op.create_index(op.f('ix_inventories_id'), 'inventories', ['id'], unique=False)
    op.create_index(op.f('ix_inventories_inventory_type'), 'inventories', ['inventory_type'], unique=False)
    op.create_index(op.f('ix_inventories_lock_token'), 'inventories', ['lock_token'], unique=True)
    op.create_index(op.f('ix_inventories_locked_until'), 'inventories', ['locked_until'], unique=False)
    op.create_index(op.f('ix_inventories_seat_id'), 'inventories', ['seat_id'], unique=True)
    op.create_index(op.f('ix_inventories_status'), 'inventories', ['status'], unique=False)
    op.create_index(op.f('ix_inventories_ticket_type_id'), 'inventories', ['ticket_type_id'], unique=True)
    op.create_index(op.f('ix_inventories_zone_id'), 'inventories', ['zone_id'], unique=False)
    op.create_index('ix_inventory_event_status', 'inventories', ['event_id', 'status'], unique=False)
    op.create_index('ix_inventory_event_type', 'inventories', ['event_id', 'inventory_type'], unique=False)
    op.create_table('seat_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lock_token', sa.String(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_active_seat_lock', 'seat_locks', ['seat_id', 'status'], unique=False)
    op.create_index('ix_lock_expiration', 'seat_locks', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_seat_locks_expires_at'), 'seat_locks', ['expires_at'], unique=False)
    op.create_index(op.f('ix_seat_locks_id'), 'seat_locks', ['id'], unique=False)
    op.create_index(op.f('ix_seat_locks_lock_token'), 'seat_locks', ['lock_token'], unique=True)
    op.create_index(op.f('ix_seat_locks_released_at'), 'seat_locks', ['released_at'], unique=False)
    op.create_index(op.f('ix_seat_locks_seat_id'), 'seat_locks', ['seat_id'], unique=False)
    op.create_index(op.f('ix_seat_locks_status'), 'seat_locks', ['status'], unique=False)
    op.create_index(op.f('ix_seat_locks_user_id'), 'seat_locks', ['user_id'], unique=False)
    op.create_index('ix_user_active_lock', 'seat_locks', ['user_id', 'status'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('ticket_type_id', sa.Integer(), nullable=True),
    sa.Column('ticket_code', sa.String(), nullable=False),
    sa.Column('qr_token', sa.String(), nullable=False),
    sa.Column('price_paid', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['event_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_booking_id'), 'tickets', ['booking_id'], unique=False)
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tickets_event_id'), 'tickets', ['event_id'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_qr_token'), 'tickets', ['qr_token'], unique=True)
    op.create_index(op.f('ix_tickets_seat_id'), 'tickets', ['seat_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_code'), 'tickets', ['ticket_code'], unique=True)
    op.create_index(op.f('ix_tickets_ticket_type_id'), 'tickets', ['ticket_type_id'], unique=False)
    op.create_index(op.f('ix_tickets_zone_id'), 'tickets', ['zone_id'], unique=False)
    op.create_table('booking_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_booking_item_price_non_negative'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'inventory_id', name='uq_booking_inventory')
    )
    op.create_index(op.f('ix_booking_items_booking_id'), 'booking_items', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_items_id'), 'booking_items', ['id'], unique=False)
    op.create_index(op.f('ix_booking_items_inventory_id'), 'booking_items', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_booking_items_status'), 'booking_items', ['status'], unique=False)
    op.drop_index(op.f('ix_seat_zones_id'), table_name='seat_zones')
    op.drop_table('seat_zones')
    op.execute("UPDATE audit_logs SET action = 'unknown' WHERE action IS NULL")
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.execute("UPDATE audit_logs SET timestamp = NOW() WHERE timestamp IS NULL")
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_audit_logs_user'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.execute("DELETE FROM blacklisted_tokens WHERE token IS NULL")
    op.alter_column('blacklisted_tokens', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('blacklisted_tokens_token_key'), 'blacklisted_tokens', type_='unique')
    op.create_index(op.f('ix_blacklisted_tokens_token'), 'blacklisted_tokens', ['token'], unique=True)
    op.add_column(
        'bookings',
        sa.Column(
            'status',
            sa.String(),
            nullable=False,
            server_default='CONFIRMED'
        )
    )

    op.execute("""
        UPDATE bookings
        SET status = 'CONFIRMED'
        WHERE status IS NULL
    """)

    op.alter_column(
        'bookings',
        'status',
        nullable=False
    )

    op.add_column(
        'bookings',
        sa.Column('total_amount', sa.Integer(), nullable=True)
    )

    op.execute("""
        UPDATE bookings
        SET total_amount = 0
        WHERE total_amount IS NULL
    """)

    op.alter_column(
        'bookings',
        'total_amount',
        nullable=False
    )

    op.add_column(
        'bookings',
        sa.Column('idempotency_key', sa.String(), nullable=True)
    )

    op.add_column(
        'bookings',
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'tickets',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'booking_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('bookings', 'payment_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bookings', 'status', server_default=None)
    op.create_index('ix_booking_event_status', 'bookings', ['event_id', 'status'], unique=False)
    op.create_index('ix_booking_expiration', 'bookings', ['status', 'expires_at'], unique=False)
    op.create_index('ix_booking_user_event', 'bookings', ['user_id', 'event_id'], unique=False)
    op.create_index(op.f('ix_bookings_booking_time'), 'bookings', ['booking_time'], unique=False)
    op.create_index(op.f('ix_bookings_event_id'), 'bookings', ['event_id'], unique=False)
    op.create_index(op.f('ix_bookings_expires_at'), 'bookings', ['expires_at'], unique=False)
    op.create_index(op.f('ix_bookings_idempotency_key'), 'bookings', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_bookings_payment_status'), 'bookings', ['payment_status'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_bookings_user'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_event_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bookings', 'user_name')
    op.execute("UPDATE categories SET name = 'Uncategorized' WHERE name IS NULL")
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('email_verifications', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("""
        UPDATE email_verifications ev
        SET user_id = u.id
        FROM users u
        WHERE ev.user_id IS NULL AND ev.username = u.username
    """)
    op.execute("DELETE FROM email_verifications WHERE user_id IS NULL")
    op.alter_column('email_verifications', 'user_id', nullable=False)
    op.execute("DELETE FROM email_verifications WHERE token IS NULL")
    op.alter_column('email_verifications', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.execute("UPDATE email_verifications SET expires_at = NOW() WHERE expires_at IS NULL")
    op.alter_column('email_verifications', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('email_verifications_token_key'), 'email_verifications', type_='unique')
    op.create_index(op.f('ix_email_verifications_expires_at'), 'email_verifications', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_verifications_token'), 'email_verifications', ['token'], unique=True)
    op.create_index(op.f('ix_email_verifications_user_id'), 'email_verifications', ['user_id'], unique=False)
    op.create_foreign_key(None, 'email_verifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('email_verifications', 'username')
    op.add_column('events', sa.Column('inventory_type', sa.String(), nullable=True, server_default='general'))
    op.execute("UPDATE events SET inventory_type = 'general' WHERE inventory_type IS NULL")
    op.alter_column('events', 'inventory_type', nullable=False)
    op.alter_column('events', 'inventory_type', server_default=None)
    op.execute("UPDATE events SET title = 'Untitled Event' WHERE title IS NULL")
    op.alter_column('events', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.execute("UPDATE events SET location = 'TBD' WHERE location IS NULL")
    op.alter_column('events', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.execute("UPDATE events SET price = 0 WHERE price IS NULL")
    op.alter_column('events', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.execute("UPDATE events SET total_seats = 0 WHERE total_seats IS NULL")
    op.alter_column('events', 'total_seats',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.execute("UPDATE events SET available_seats = 0 WHERE available_seats IS NULL")
    op.alter_column('events', 'available_seats',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_events_category_id'), 'events', ['category_id'], unique=False)
    op.create_index(op.f('ix_events_inventory_type'), 'events', ['inventory_type'], unique=False)
    op.execute("UPDATE notifications SET message = '' WHERE message IS NULL")
    op.alter_column('notifications', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.execute("UPDATE notifications SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_notifications_user'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'user_name')
    op.alter_column('otp_verifications', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.execute("UPDATE otp_verifications SET attempts = 0 WHERE attempts IS NULL")
    op.alter_column('otp_verifications', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.execute("UPDATE otp_verifications SET verified = false WHERE verified IS NULL")
    op.alter_column('otp_verifications', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.execute("UPDATE otp_verifications SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column('otp_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('otp_verifications', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('otp_verifications', 'verification_token_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_otp_verifications_expires_at'), 'otp_verifications', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_verifications_id'), 'otp_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_otp_verifications_purpose'), 'otp_verifications', ['purpose'], unique=False)
    op.create_index(op.f('ix_otp_verifications_user_id'), 'otp_verifications', ['user_id'], unique=False)
    op.drop_constraint(op.f('otp_verifications_user_id_fkey'), 'otp_verifications', type_='foreignkey')
    op.create_foreign_key(None, 'otp_verifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('password_resets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("""
        UPDATE password_resets pr
        SET user_id = u.id
        FROM users u
        WHERE pr.user_id IS NULL AND pr.username = u.username
    """)
    op.execute("DELETE FROM password_resets WHERE user_id IS NULL")
    op.alter_column('password_resets', 'user_id', nullable=False)
    op.execute("DELETE FROM password_resets WHERE token IS NULL")
    op.alter_column('password_resets', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.execute("UPDATE password_resets SET expires_at = NOW() WHERE expires_at IS NULL")
    op.alter_column('password_resets', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('password_resets_token_key'), 'password_resets', type_='unique')
    op.create_index(op.f('ix_password_resets_expires_at'), 'password_resets', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_resets_token'), 'password_resets', ['token'], unique=True)
    op.create_index(op.f('ix_password_resets_user_id'), 'password_resets', ['user_id'], unique=False)
    op.create_foreign_key(None, 'password_resets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('password_resets', 'username')
    op.add_column('payments', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('provider_payment_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('currency', sa.String(), nullable=True, server_default='INR'))
    op.execute("UPDATE payments SET currency = 'INR' WHERE currency IS NULL")
    op.alter_column('payments', 'currency', nullable=False)
    op.alter_column('payments', 'currency', server_default=None)
    op.add_column('payments', sa.Column('failure_reason', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('webhook_event_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE payments SET updated_at = COALESCE(created_at, NOW()) WHERE updated_at IS NULL")
    op.alter_column('payments', 'updated_at', nullable=False)
    # A payment row with no booking_id or user_id is orphaned data with no safe FK value to invent —
    # delete rather than silently corrupt financial records with a fabricated reference.
    op.execute("DELETE FROM payments WHERE booking_id IS NULL OR user_id IS NULL")
    op.alter_column('payments', 'booking_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.execute("UPDATE payments SET amount = 0 WHERE amount IS NULL")
    op.alter_column('payments', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.execute("UPDATE payments SET status = 'pending' WHERE status IS NULL")
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.execute("UPDATE payments SET method = 'mock' WHERE method IS NULL")
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.execute("UPDATE payments SET transaction_id = 'legacy-' || id::text WHERE transaction_id IS NULL")
    op.alter_column('payments', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.execute("UPDATE payments SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('payments_transaction_id_key'), 'payments', type_='unique')
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=True)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_payments_webhook_event_id'), 'payments', ['webhook_event_id'], unique=True)
    op.drop_constraint(op.f('payments_booking_id_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('fk_payments_user'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.drop_column('payments', 'user_name')
    # Backfill NULLs with safe, non-guessable placeholders before tightening to NOT NULL.
    # 'INVALID_LEGACY_HASH' can never match a real bcrypt/password hash, so an affected
    # account simply can't log in until a password reset — never fall back to an empty
    # password, which could open a blank-password login hole.
    op.execute("UPDATE users SET username = 'user_' || id::text WHERE username IS NULL")
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.execute("UPDATE users SET password = 'INVALID_LEGACY_HASH' WHERE password IS NULL")
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.execute("UPDATE users SET is_active = true WHERE is_active IS NULL")
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.execute("UPDATE users SET is_verified = false WHERE is_verified IS NULL")
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.execute("UPDATE users SET email_verified = false WHERE email_verified IS NULL")
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.execute("UPDATE users SET phone_verified = false WHERE phone_verified IS NULL")
    op.alter_column('users', 'phone_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.execute("UPDATE users SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.execute("UPDATE users SET updated_at = NOW() WHERE updated_at IS NULL")
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_phone_key'), 'users', type_='unique')
    op.drop_index(op.f('users_phone_lookup_hmac_key'), table_name='users')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_phone_lookup_hmac'), 'users', ['phone_lookup_hmac'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_lookup_hmac'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('users_phone_lookup_hmac_key'), 'users', ['phone_lookup_hmac'], unique=True)
    op.create_unique_constraint(op.f('users_phone_key'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'phone_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('payments', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_payments_user'), 'payments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('payments_booking_id_fkey'), 'payments', 'bookings', ['booking_id'], ['id'])
    op.drop_index(op.f('ix_payments_webhook_event_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.create_unique_constraint(op.f('payments_transaction_id_key'), 'payments', ['transaction_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('payments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('payments', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'booking_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'paid_at')
    op.drop_column('payments', 'webhook_event_id')
    op.drop_column('payments', 'failure_reason')
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'provider_payment_id')
    op.drop_column('payments', 'provider')
    op.add_column('password_resets', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'password_resets', type_='foreignkey')
    op.drop_index(op.f('ix_password_resets_user_id'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_token'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_expires_at'), table_name='password_resets')
    op.create_unique_constraint(op.f('password_resets_token_key'), 'password_resets', ['token'], postgresql_nulls_not_distinct=False)
    op.alter_column('password_resets', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('password_resets', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('password_resets', 'user_id')
    op.drop_constraint(None, 'otp_verifications', type_='foreignkey')
    op.create_foreign_key(op.f('otp_verifications_user_id_fkey'), 'otp_verifications', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_otp_verifications_user_id'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_purpose'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_id'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_expires_at'), table_name='otp_verifications')
    op.alter_column('otp_verifications', 'verification_token_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('otp_verifications', 'used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('otp_verifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('otp_verifications', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('otp_verifications', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('otp_verifications', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('notifications', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('fk_notifications_user'), 'notifications', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_events_inventory_type'), table_name='events')
    op.drop_index(op.f('ix_events_category_id'), table_name='events')
    op.alter_column('events', 'available_seats',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'total_seats',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('events', 'inventory_type')
    op.add_column('email_verifications', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'email_verifications', type_='foreignkey')
    op.drop_index(op.f('ix_email_verifications_user_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_token'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_expires_at'), table_name='email_verifications')
    op.create_unique_constraint(op.f('email_verifications_token_key'), 'email_verifications', ['token'], postgresql_nulls_not_distinct=False)
    op.alter_column('email_verifications', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('email_verifications', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('email_verifications', 'user_id')
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('bookings', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_event_id_fkey'), 'bookings', 'events', ['event_id'], ['id'])
    op.create_foreign_key(op.f('fk_bookings_user'), 'bookings', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_payment_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_idempotency_key'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_expires_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_event_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_time'), table_name='bookings')
    op.drop_index('ix_booking_user_event', table_name='bookings')
    op.drop_index('ix_booking_expiration', table_name='bookings')
    op.drop_index('ix_booking_event_status', table_name='bookings')
    op.alter_column('bookings', 'payment_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bookings', 'booking_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bookings', 'tickets',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('bookings', 'expires_at')
    op.drop_column('bookings', 'idempotency_key')
    op.drop_column('bookings', 'total_amount')
    op.drop_column('bookings', 'status')
    op.drop_index(op.f('ix_blacklisted_tokens_token'), table_name='blacklisted_tokens')
    op.create_unique_constraint(op.f('blacklisted_tokens_token_key'), 'blacklisted_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.alter_column('blacklisted_tokens', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_logs_user'), 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.alter_column('audit_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('seat_zones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_seats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('available_seats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zone_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('seat_zones_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('seat_zones_pkey'))
    )
    op.create_index(op.f('ix_seat_zones_id'), 'seat_zones', ['id'], unique=False)
    op.drop_index(op.f('ix_booking_items_status'), table_name='booking_items')
    op.drop_index(op.f('ix_booking_items_inventory_id'), table_name='booking_items')
    op.drop_index(op.f('ix_booking_items_id'), table_name='booking_items')
    op.drop_index(op.f('ix_booking_items_booking_id'), table_name='booking_items')
    op.drop_table('booking_items')
    op.drop_index(op.f('ix_tickets_zone_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_ticket_type_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_ticket_code'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_seat_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_qr_token'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_event_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_booking_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_user_active_lock', table_name='seat_locks')
    op.drop_index(op.f('ix_seat_locks_user_id'), table_name='seat_locks')
    op.drop_index(op.f('ix_seat_locks_status'), table_name='seat_locks')
    op.drop_index(op.f('ix_seat_locks_seat_id'), table_name='seat_locks')
    op.drop_index(op.f('ix_seat_locks_released_at'), table_name='seat_locks')
    op.drop_index(op.f('ix_seat_locks_lock_token'), table_name='seat_locks')
    op.drop_index(op.f('ix_seat_locks_id'), table_name='seat_locks')
    op.drop_index(op.f('ix_seat_locks_expires_at'), table_name='seat_locks')
    op.drop_index('ix_lock_expiration', table_name='seat_locks')
    op.drop_index('ix_active_seat_lock', table_name='seat_locks')
    op.drop_table('seat_locks')
    op.drop_index('ix_inventory_event_type', table_name='inventories')
    op.drop_index('ix_inventory_event_status', table_name='inventories')
    op.drop_index(op.f('ix_inventories_zone_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_ticket_type_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_status'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_seat_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_locked_until'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_lock_token'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_inventory_type'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_event_id'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_index(op.f('ix_seats_zone_id'), table_name='seats')
    op.drop_index(op.f('ix_seats_status'), table_name='seats')
    op.drop_index(op.f('ix_seats_seat_code'), table_name='seats')
    op.drop_index(op.f('ix_seats_row_id'), table_name='seats')
    op.drop_index(op.f('ix_seats_is_active'), table_name='seats')
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_index(op.f('ix_seats_event_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_venue_rows_zone_id'), table_name='venue_rows')
    op.drop_index(op.f('ix_venue_rows_id'), table_name='venue_rows')
    op.drop_index(op.f('ix_venue_rows_event_id'), table_name='venue_rows')
    op.drop_table('venue_rows')
    op.drop_index(op.f('ix_ticket_types_zone_id'), table_name='ticket_types')
    op.drop_index(op.f('ix_ticket_types_is_active'), table_name='ticket_types')
    op.drop_index(op.f('ix_ticket_types_id'), table_name='ticket_types')
    op.drop_index(op.f('ix_ticket_types_event_id'), table_name='ticket_types')
    op.drop_table('ticket_types')
    op.drop_index(op.f('ix_event_zones_zone_type'), table_name='event_zones')
    op.drop_index(op.f('ix_event_zones_layout_id'), table_name='event_zones')
    op.drop_index(op.f('ix_event_zones_is_active'), table_name='event_zones')
    op.drop_index(op.f('ix_event_zones_id'), table_name='event_zones')
    op.drop_index(op.f('ix_event_zones_event_id'), table_name='event_zones')
    op.drop_table('event_zones')
    op.drop_index(op.f('ix_venue_layouts_is_active'), table_name='venue_layouts')
    op.drop_index(op.f('ix_venue_layouts_id'), table_name='venue_layouts')
    op.drop_index(op.f('ix_venue_layouts_event_id'), table_name='venue_layouts')
    op.drop_index('ix_layout_event_active', table_name='venue_layouts')
    op.drop_table('venue_layouts')
    # ### end Alembic commands ###