"""empty message

Revision ID: 4e74288bee93
Revises: 580df8c6e54f
Create Date: 2026-08-30 13:20:34.297039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e74288bee93'
down_revision: Union[str, Sequence[str], None] = '580df8c6e54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: pehle nullable column add karo (koi constraint violation nahi hoga)
    op.add_column('events', sa.Column('status', sa.String(), nullable=True))

    # Step 2: saari existing rows ko default value se bharo
    op.execute("UPDATE events SET status = 'published' WHERE status IS NULL")

    # Step 3: ab NOT NULL constraint lagao, kyunki sab rows filled ho chuki hain
    op.alter_column('events', 'status', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'status')
    # ### end Alembic commands ###
