"""add age_limit and duration to events

Revision ID: 580df8c6e54f
Revises: 837d0ec026e5
Create Date: 2026-08-29 00:36:20.219656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '580df8c6e54f'
down_revision: Union[str, Sequence[str], None] = '837d0ec026e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_booking_item_quantity_positive', 'booking_items', 'quantity > 0')
    op.add_column('events', sa.Column('age_limit', sa.String(), nullable=True))
    op.add_column('events', sa.Column('duration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'duration')
    op.drop_column('events', 'age_limit')
    op.drop_constraint('ck_booking_item_quantity_positive', 'booking_items', type_='check')
    # ### end Alembic commands ###
